import { Request, Response } from "express";
import { sumonnerRepository } from "../repositories/SumonnerRepository";
import { infoMatchRepository } from "../repositories/InfoMatchRepository";

export default class InfoMatchController {
  async create(req: Request, res: Response) {
    const {    
        idjogo,
		datacriacaodojogo,
		duracaodojogo,
		assistencias,
		baroeseliminados,
		nivelcampeao,
		nomecampeao,
		danoobejtivos,
		danoedificios,
		danotorres,
		danomitigado,
		mortes,
		detectorwards,
		doublekills,
		dragaoelimininados,
		assistenciaprimeiroabate,
		primeiroabate,
		assistenciaprimeiratorre,
		abateprimeiratorre,
		jogoterminourendicaoantecipada,
		jogoterminourendicao,
		ouroganho,
		ourogasto,
		posicaoindividual,
		inibidordestruidos,
		inibidordestruidoequipe,
		inibidorperdido,
		item0,
		item1,
		item2,
		item3,
		item4,
		item5,
		item6,
		killingsprees,
		abates,
		lane,
		maioracertocritico,
		danomagicocausado,
		danomagicocausadocampeoes,
		objetivosroubados,
		pentakills,
		danofisicocausado,
		danofisicocausadocampeoes,
		puuid,
		quadrakills,
		role,
		pinkscompradas,
		nivelinvocador,
		nomeinvocador,
		tempoccoutros,
		totaldanocausado,
		totaldanocausadocampeos,
		totaldanoprotegidoemaliano,
		totaldedanorecebido,
		totaldecurasrecebidas,
		totalminioneliminados,
		totalcccausado,
		totaltempomorto,
		triplekills,
		torredestruidas,
		torreassistencia,
		mortesfordas,
		placardevisao,
		visaowardscompradanojogo,
		wardscolocadas,
		vitoria,
		fila
    } = req.body;

    try {
      const newInfoMatch = infoMatchRepository.create({
        idjogo,
		datacriacaodojogo,
		duracaodojogo,
		assistencias,
		baroeseliminados,
		nivelcampeao,
		nomecampeao,
		danoobejtivos,
		danoedificios,
		danotorres,
		danomitigado,
		mortes,
		detectorwards,
		doublekills,
		dragaoelimininados,
		assistenciaprimeiroabate,
		primeiroabate,
		assistenciaprimeiratorre,
		abateprimeiratorre,
		jogoterminourendicaoantecipada,
		jogoterminourendicao,
		ouroganho,
		ourogasto,
		posicaoindividual,
		inibidordestruidos,
		inibidordestruidoequipe,
		inibidorperdido,
		item0,
		item1,
		item2,
		item3,
		item4,
		item5,
		item6,
		killingsprees,
		abates,
		lane,
		maioracertocritico,
		danomagicocausado,
		danomagicocausadocampeoes,
		objetivosroubados,
		pentakills,
		danofisicocausado,
		danofisicocausadocampeoes,
		puuid,
		quadrakills,
		role,
		pinkscompradas,
		nivelinvocador,
		nomeinvocador,
		tempoccoutros,
		totaldanocausado,
		totaldanocausadocampeos,
		totaldanoprotegidoemaliano,
		totaldedanorecebido,
		totaldecurasrecebidas,
		totalminioneliminados,
		totalcccausado,
		totaltempomorto,
		triplekills,
		torredestruidas,
		torreassistencia,
		mortesfordas,
		placardevisao,
		visaowardscompradanojogo,
		wardscolocadas,
		vitoria,
		fila,
      });

      await infoMatchRepository.save(newInfoMatch);

      return res.status(201).json(newInfoMatch);
    } catch (error) {
      console.error(error);
      return res.status(500).json({ error });
    }
  }
}
